<?php

return [
	'AED' => [
		'symbol' => 'د.إ.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 784,
	],
	'AFN' => [
		'symbol' => '؋',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 4,
	],
	'ALL' => [
		'symbol' => 'L',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 8,
	],
	'AMD' => [
		'symbol' => '֏',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 51,
	],
	'AOA' => [
		'symbol' => 'Kz',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 982,
	],
	'ARS' => [
		'symbol' => 'AR$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 32,
	],
	'AUD' => [
		'symbol' => 'A$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 36,
	],
	'AWG' => [
		'symbol' => 'ƒ',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 533,
	],
	'AZN' => [
		'symbol' => '₼',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 944,
	],
	'BAM' => [
		'symbol' => 'KM',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 977,
	],
	'BBD' => [
		'symbol' => 'BB$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 52,
	],
	'BDT' => [
		'symbol' => '৳',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 50,
	],
	'BGN' => [
		'symbol' => 'лв',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 975,
	],
	'BHD' => [
		'symbol' => 'د.ب.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 48,
	],
	'BIF' => [
		'symbol' => 'FBu',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 108,
	],
	'BMD' => [
		'symbol' => 'BD$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 60,
	],
	'BND' => [
		'symbol' => 'BN$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 96,
	],
	'BOB' => [
		'symbol' => 'Bs.',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 68,
	],
	'BRL' => [
		'symbol' => 'R$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 986,
	],
	'BSD' => [
		'symbol' => 'B$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 44,
	],
	'BTC' => [
		'symbol' => '₿',
		'template' => '$1',
		'decimals' => 8,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'BTN' => [
		'symbol' => 'Nu.',
		'template' => '$ 1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 64,
	],
	'BWP' => [
		'symbol' => 'P',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 72,
	],
	'BYR' => [
		'symbol' => 'р.',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'BZD' => [
		'symbol' => 'BZ$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 84,
	],
	'CAD' => [
		'symbol' => 'CA$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 124,
	],
	'CDF' => [
		'symbol' => 'FC',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'CHF' => [
		'symbol' => 'Fr.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 756,
	],
	'CLP' => [
		'symbol' => 'CLP$',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 152,
	],
	'CNY' => [
		'symbol' => '¥',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 156,
	],
	'COP' => [
		'symbol' => 'COL$',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 170,
	],
	'CRC' => [
		'symbol' => '₡',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 188,
	],
	'CUP' => [
		'symbol' => '₱',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 192,
	],
	'CVE' => [
		'symbol' => 'Esc$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 132,
	],
	'CZK' => [
		'symbol' => 'Kč',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 200,
	],
	'DJF' => [
		'symbol' => 'Fdj',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 262,
	],
	'DKK' => [
		'symbol' => 'kr',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 208,
	],
	'DOP' => [
		'symbol' => 'RD$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 214,
	],
	'DZD' => [
		'symbol' => 'د.ج.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 12,
	],
	'EGP' => [
		'symbol' => 'ج.م.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 818,
	],
	'ERN' => [
		'symbol' => 'Nkf',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 232,
	],
	'ETB' => [
		'symbol' => 'Br',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 230,
	],
	'ETH' => [
		'symbol' => 'Ξ',
		'template' => '$ 1',
		'decimals' => 18,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'EUR' => [
		'symbol' => '€',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 978,
	],
	'FJD' => [
		'symbol' => 'FJ$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 242,
	],
	'FKP' => [
		'symbol' => 'FK£',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 238,
	],
	'GBP' => [
		'symbol' => '£',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 826,
	],
	'GEL' => [
		'symbol' => '₾',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 981,
	],
	'GHS' => [
		'symbol' => '₵',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 936,
	],
	'GIP' => [
		'symbol' => '£',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 292,
	],
	'GMD' => [
		'symbol' => 'D',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 270,
	],
	'GNF' => [
		'symbol' => 'FG',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 324,
	],
	'GTQ' => [
		'symbol' => 'Q',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 320,
	],
	'GYD' => [
		'symbol' => 'G$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 328,
	],
	'HKD' => [
		'symbol' => 'HK$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 344,
	],
	'HNL' => [
		'symbol' => 'L',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 340,
	],
	'HRK' => [
		'symbol' => 'kn',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 191,
	],
	'HTG' => [
		'symbol' => 'G',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 332,
	],
	'HUF' => [
		'symbol' => 'Ft',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 348,
	],
	'IDR' => [
		'symbol' => 'Rp',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 360,
	],
	'ILS' => [
		'symbol' => '₪',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 376,
	],
	'INR' => [
		'symbol' => '₹',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 356,
	],
	'IQD' => [
		'symbol' => 'د.ع.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 368,
	],
	'IRR' => [
		'symbol' => '﷼',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 364,
	],
	'ISK' => [
		'symbol' => 'kr',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 352,
	],
	'JMD' => [
		'symbol' => 'J$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 388,
	],
	'JOD' => [
		'symbol' => 'د.أ.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 400,
	],
	'JPY' => [
		'symbol' => '¥',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 392,
	],
	'KES' => [
		'symbol' => 'KSh',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 404,
	],
	'KGS' => [
		'symbol' => 'сом',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 417,
	],
	'KHR' => [
		'symbol' => '៛',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 116,
	],
	'KMF' => [
		'symbol' => 'CF',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 174,
	],
	'KPW' => [
		'symbol' => '₩',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 408,
	],
	'KRW' => [
		'symbol' => '₩',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 410,
	],
	'KWD' => [
		'symbol' => 'د.ك.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 414,
	],
	'KYD' => [
		'symbol' => 'CI$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 136,
	],
	'KZT' => [
		'symbol' => '₸',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 398,
	],
	'LAK' => [
		'symbol' => '₭',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 418,
	],
	'LBP' => [
		'symbol' => 'ل.ل.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 422,
	],
	'LRD' => [
		'symbol' => 'L$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 430,
	],
	'LSL' => [
		'symbol' => 'L',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 426,
	],
	'LTL' => [
		'symbol' => 'Lt',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 440,
	],
	'LYD' => [
		'symbol' => 'د.ل.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 434,
	],
	'MAD' => [
		'symbol' => 'د.م.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 504,
	],
	'MDL' => [
		'symbol' => 'L',
		'template' => '$ 1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 498,
	],
	'MGA' => [
		'symbol' => 'Ar',
		'template' => '1 $',
		'decimals' => 1,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 969,
	],
	'MKD' => [
		'symbol' => 'ден',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 807,
	],
	'MMK' => [
		'symbol' => 'Ks',
		'template' => '$ 1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 104,
	],
	'MNT' => [
		'symbol' => '₮',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 496,
	],
	'MOP' => [
		'symbol' => 'MOP$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 446,
	],
	'MRO' => [
		'symbol' => 'ouguiya',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 478,
	],
	'MUR' => [
		'symbol' => '₨',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 480,
	],
	'MVR' => [
		'symbol' => 'ރ',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 462,
	],
	'MWK' => [
		'symbol' => 'MK',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 454,
	],
	'MXN' => [
		'symbol' => 'MX$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 484,
	],
	'MYR' => [
		'symbol' => 'RM',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 458,
	],
	'MZN' => [
		'symbol' => 'MT',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 943,
	],
	'NAD' => [
		'symbol' => 'N$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 516,
	],
	'NGN' => [
		'symbol' => '₦',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 566,
	],
	'NIO' => [
		'symbol' => 'C$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 558,
	],
	'NOK' => [
		'symbol' => 'kr',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 578,
	],
	'NPR' => [
		'symbol' => '₨',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 524,
	],
	'NZD' => [
		'symbol' => 'NZ$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 554,
	],
	'OMR' => [
		'symbol' => 'ر.ع.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 512,
	],
	'PAB' => [
		'symbol' => 'B/.',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 590,
	],
	'PEN' => [
		'symbol' => 'S/',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 604,
	],
	'PGK' => [
		'symbol' => 'K',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 598,
	],
	'PHP' => [
		'symbol' => '₱',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 608,
	],
	'PKR' => [
		'symbol' => '₨',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 586,
	],
	'PLN' => [
		'symbol' => 'zł',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 985,
	],
	'PYG' => [
		'symbol' => '₲',
		'template' => '1$',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 600,
	],
	'QAR' => [
		'symbol' => 'ر.ق.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 634,
	],
	'RON' => [
		'symbol' => 'lei',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 946,
	],
	'RSD' => [
		'symbol' => 'Дин.',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 941,
	],
	'RUB' => [
		'symbol' => '₽',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 643,
	],
	'RWF' => [
		'symbol' => 'R₣',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 646,
	],
	'SAR' => [
		'symbol' => '﷼',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 682,
	],
	'SBD' => [
		'symbol' => 'SI$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 90,
	],
	'SCR' => [
		'symbol' => '₨',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 690,
	],
	'SDG' => [
		'symbol' => 'ج.س.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 736,
	],
	'SEK' => [
		'symbol' => 'kr',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 752,
	],
	'SGD' => [
		'symbol' => 'S$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 702,
	],
	'SHP' => [
		'symbol' => '£',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'SLL' => [
		'symbol' => 'Le',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 694,
	],
	'SOS' => [
		'symbol' => 'Sh.So.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 706,
	],
	'SRD' => [
		'symbol' => 'SR$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 968,
	],
	'STD' => [
		'symbol' => 'Db',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'SYP' => [
		'symbol' => 'ل.س.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 760,
	],
	'SZL' => [
		'symbol' => 'E',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 748,
	],
	'THB' => [
		'symbol' => '฿',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 764,
	],
	'TJS' => [
		'symbol' => 'SM',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 762,
	],
	'TMT' => [
		'symbol' => 'm.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 795,
	],
	'TND' => [
		'symbol' => 'د.ت.',
		'template' => '1 $',
		'decimals' => 3,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 788,
	],
	'TOP' => [
		'symbol' => 'T$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 776,
	],
	'TRY' => [
		'symbol' => '₺',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 949,
	],
	'TTD' => [
		'symbol' => 'TT$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 780,
	],
	'TWD' => [
		'symbol' => 'NT$',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 901,
	],
	'TZS' => [
		'symbol' => 'TSh',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 834,
	],
	'UAH' => [
		'symbol' => '₴',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 980,
	],
	'UGX' => [
		'symbol' => 'USh',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 800,
	],
	'USD' => [
		'symbol' => '$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 840,
	],
	'UYU' => [
		'symbol' => '$U',
		'template' => '$1',
		'decimals' => 0,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 858,
	],
	'UZS' => [
		'symbol' => 'so’m',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 860,
	],
	'VEF' => [
		'symbol' => 'Bs',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 937,
	],
	'VND' => [
		'symbol' => '₫',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => ',',
		'thousands_separator' => '.',
		'iso_number' => 704,
	],
	'VUV' => [
		'symbol' => 'VT',
		'template' => '1$',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 548,
	],
	'WST' => [
		'symbol' => 'WS$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 882,
	],
	'XAF' => [
		'symbol' => 'FCFA',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => null,
	],
	'XCD' => [
		'symbol' => 'EC$',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 951,
	],
	'XOF' => [
		'symbol' => 'CFA',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 952,
	],
	'XPF' => [
		'symbol' => '₣',
		'template' => '1 $',
		'decimals' => 0,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 953,
	],
	'YER' => [
		'symbol' => 'ر.ي.',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 886,
	],
	'ZAR' => [
		'symbol' => 'R',
		'template' => '$1',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 710,
	],
	'ZMW' => [
		'symbol' => 'ZK',
		'template' => '1 $',
		'decimals' => 2,
		'decimals_separator' => '.',
		'thousands_separator' => ',',
		'iso_number' => 967,
	],
];
